config/routes.rb
Rails.application.routes.draw do
  resources :resposta_pagseguros

end

app/models/resposta_pagseguro.rb
class RespostaPagseguro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/resposta_pagseguros_controller.rb
class RespostaPagsegurosController < ApplicationController
  before_action :set_resposta_pagseguro, only: [:show]

  # GET /resposta_pagseguros
  # GET /resposta_pagseguros.json
  def index
    @resposta_pagseguros = RespostaPagseguro.all
  end

  # GET /resposta_pagseguros/1
  # GET /resposta_pagseguros/1.json
  def show
  end

  # POST /resposta_pagseguros
  # POST /resposta_pagseguros.json
  def create
    @resposta_pagseguro = RespostaPagseguro.new(resposta_pagseguro_params)

    respond_to do |format|
      if @resposta_pagseguro.save
        format.html { redirect_to @resposta_pagseguro, notice: 'Resposta pagseguro was successfully created.' }
        format.json { render :show, status: :created, location: @resposta_pagseguro }
      else
        format.html { render :new }
        format.json { render json: @resposta_pagseguro.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resposta_pagseguro
      @resposta_pagseguro = RespostaPagseguro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resposta_pagseguro_params      
      params[:resposta_pagseguro] = {notificationCode: params[:notificationCode], notificationType: params[:notificationType]}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resposta_pagseguros_helper.rb
module RespostaPagsegurosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookmakerPagseguroSandbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resposta_pagseguros/_form.html.erb
<%= form_for(@resposta_pagseguro) do |f| %>
  <% if @resposta_pagseguro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resposta_pagseguro.errors.count, "error") %> prohibited this resposta_pagseguro from being saved:</h2>

      <ul>
      <% @resposta_pagseguro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resposta_pagseguros/edit.html.erb
<h1>Editing Resposta Pagseguro</h1>

<%= render 'form' %>

<%= link_to 'Show', @resposta_pagseguro %> |
<%= link_to 'Back', resposta_pagseguros_path %>

app/views/resposta_pagseguros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resposta Pagseguros</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resposta_pagseguros.each do |resposta_pagseguro| %>
      <tr>
        <td><%= link_to 'Show', resposta_pagseguro %></td>
        <td><%= link_to 'Edit', edit_resposta_pagseguro_path(resposta_pagseguro) %></td>
        <td><%= link_to 'Destroy', resposta_pagseguro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resposta pagseguro', new_resposta_pagseguro_path %>

app/views/resposta_pagseguros/new.html.erb
<h1>New Resposta Pagseguro</h1>

<%= render 'form' %>

<%= link_to 'Back', resposta_pagseguros_path %>

app/views/resposta_pagseguros/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resposta_pagseguro_path(@resposta_pagseguro) %> |
<%= link_to 'Back', resposta_pagseguros_path %>